### ISSUE TITLE
Documentation page tracking

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1309]
- When 'should be tracked' is checked, the answers are only shown on the results page if the download button at the end of the documentation page is clicked. This button still says download on it even though its function now seems to be submit instead. I suggest there should be two buttons 'download' will always download a PDF and 'submit' will only appear when tracking is on and the answers will be submitted to the results page. Perhaps there should be also an option to remove the download button when tracking is on as a submit & download button might not always be required together
- 'Should be tracked' option should be reworded - I suggest 'Submit answers' might be more appropriate if a submit button is added. This could also do with a tooltip to explain that this will track answers and surface them on the results page / adaptive content page

**Comment by FayCross** [comment]
Additional comments on this functionality:

- [ ] The conditions related to the 'show download button' are reversed - file orientation, font size and file name are hidden when the box is checked and are shown when the box is checked. Also, need to check how this worked before recent changes. If the download button was always shown by default then these options should be shown even if the show download button optional property has not been added
- [ ] There should be some on screen confirmation after the submit answers buttons has been clicked. At the moment the button just disappears. There should be something that at least says 'your answers have been submitted' This should be a language string that is editable if you click the 'show language options' box in the editor
- [ ] The submit button disappears after it's clicked - should it? If you edit your answers after submitting, will these be shown on the results page or just the version that was there when you clicked submit?
- [ ] Even when submit answers is on and I click submit, no info appears on the results page. Not sure what is going wrong but I think this worked the first time I tested this?

**Comment by FayCross** [comment]
@torinfo the issues I previously found here are all working well now.
There is something odd on the data shown on the results page though - if an image or description block has been added to the page then these show listed in the interactivity results even though there is nothing to associated with them that can be answered or submitted.
