### ISSUE TITLE
Other issues/fixes suggested by John Horne on the forum

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#565]
- [x] Xerte 3.3: upgrade.php - step 5 - trivial bug http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1237&Itemid=759&lang=en#4237

- [x] Xerte 3.3: deleting templates bug - http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1234&Itemid=759&lang=en#4233

- [x] v3: Bug: Playing youtu.be video fails - http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=955&Itemid=207&lang=en#3151

**Comment by jayaich** [comment]
The deleting templates bug has now gone in as pull request #669.
The 'youtu.be' bug seems to have been fixed in version 3.4 (maybe before that).
I would say that this whole issue can be closed now.
