### ISSUE TITLE
Possible SCORM/Tracking enhancements to add at some point...

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#775]
- [ ] 1.	An optional property override for the ‘Page timeout for completion’ where that timeout can be reduced or increased for particular pages. I know we have the option for each page to not track but I think there’s a need for more control at page level for the duration setting. E.g. 1 second for a title page, much longer for a multi-page navigator.
- [ ] 2.	An optional but simple debug mode where as a tester navigates and interacts very basic info is displayed re completion/score etc.
- [ ] 3.	You mentioned that you’ve created an end page Tom – perhaps and optional property to indicate with a simple message to a user that some pages aren’t yet marked as complete and a prompt to check the TOC and/or review skipped pages.
